server:
  port: 8081
spring:
  application:
    name: eureka_client_one
  boot:
    admin:
      client:
        url: http://127.0.0.1:5000
management:
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/