server:
  port: 8080

spring:
  application:
    name: admin_client
  boot:
    admin:
      client:
        url: http://127.0.0.1:5000


management:
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/